# Welcome to jzhstudio

# Website settings
title: "jzhstudio"
description: "My Wordl."
keywords: "My World"
baseurl: "/"
url: "http://jzhstudio.github.io"
# url: "http://127.0.0.1:4000"

# author
author:
  name: 'jzh'
  first_name: 'Jiao'
  last_name: 'Zihang'
  email: '79373654@qq.com'
  facebook_username: 'jzh'
  github_username: 'jzhstudio'
  head_img: 'static/img/landing/jj.jpg'
  desc: '°®Éú»î£¬°®ÕÛÌÚ'

# sections
sections:
  - id: 'about-me'
    i18n: 'nav.about_me'
    name: 'About'
    tpl: 'about.html'
    css: ''

  - id: 'career'
    i18n: 'nav.career'
    name: 'Career'
    tpl: 'career.html'
    css: 'timeline'

  - id: 'skills'
    i18n: 'nav.skills'
    name: 'Skills'
    tpl: 'skills.html'
    css: 'team'

  - id: 'projects'
    i18n: 'nav.projects'
    name: 'Projects'
    tpl: 'projects.html'
    css: 'project'

  - id: 'blog'
    i18n: 'nav.blog'
    name: 'Blog'
    tpl: 'blog.html'
    css: 'testimonials navy-section'

  - id: 'links'
    i18n: 'nav.link'
    name: 'Links'
    tpl: 'links.html'
    css: 'contact'

# localization
languages:
  - locale: 'en'
    flag: 'static/img/flags/United-States.png'
  - locale: 'zh'
    flag: 'static/img/flags/China.png'

# blog img path
img_path: 'http://www.jack003.com/static/img/blog'

# donate
donate:
  wechat: 'static/img/pay/wechat.jpg'
  alipay: 'static/img/pay/qq.png'

# comment
changyan:
  # appid: cysfY7ULn
  # conf: prod_861928934cecb7a18e15bedaed9dae29
disqus:
  name: jalpc
  public_key: tj2MPaNlHMONwTH5bGDNSXyaBpW7q282MeUzh5CwcjJerNhK8Kxk3aWo7IckzTX7

# share
bshare:
  uuid: 513f778e-a8f7-4c20-9ec2-d29cc2328d75

# baidu analytics
ba:
  uuid: 317acca9ef9255b934e46371e471431d

# google analytics
ga:
  id: UA-73784599-1

# Build settings
encoding: "utf-8"

# other settings
highlighter: rouge
markdown: kramdown
kramdown:
  input: GFM
  syntax_highlighter: rouge
